name: gridddtest
favicon: null
layout_spectrum: 0.74587
typography_spectrum: 0.8807349123526365
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#425c77'
    - '#e5e7e9'
    - '#84a2b4'
    - '#000000'
    - '#bdb5b9'
  brandStrength: 0.6875
  lightness: 0.3521995940245688
  saturation: 0.10313049308024347
  rhythmicContrast: 0.33060701680369675
purpose: []
